from flask import Flask, request, send_file, jsonify, send_from_directory
from flask_cors import CORS
from flask_sqlalchemy import SQLAlchemy
from dotenv import load_dotenv
import os
from datetime import datetime
from io import BytesIO

load_dotenv()

app = Flask(__name__)
if os.getenv('VERCEL'):
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/history.db'
else:
    # Ensure data directory exists locally
    os.makedirs('data', exist_ok=True)
    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{os.getenv('DATABASE_URL', 'data/history.db')}"

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
CORS(app)

db = SQLAlchemy(app)

class History(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    session_id = db.Column(db.String(255), nullable=False, index=True)
    algorithm = db.Column(db.String(50), nullable=False)
    mode = db.Column(db.String(10), nullable=False)
    operation_type = db.Column(db.String(20), nullable=False)
    input_size = db.Column(db.Integer, nullable=False)
    output_size = db.Column(db.Integer, nullable=False)
    status = db.Column(db.String(20), nullable=False, default='success')
    ip_address = db.Column(db.String(45))

    def to_dict(self):
        return {
            'id': self.id,
            'timestamp': self.timestamp.strftime('%Y-%m-%d %H:%M:%S'),
            'algorithm': self.algorithm,
            'mode': self.mode,
            'operation_type': self.operation_type,
            'input_size': self.input_size,
            'output_size': self.output_size,
            'status': self.status
        }

@app.route('/', defaults={'path': 'index.html'})
@app.route('/<path:path>')
def serve_static(path):
    if path == '':
        path = 'index.html'
    return send_from_directory('.', path)

@app.route('/api/home')
def home():
    with app.app_context():
        return jsonify({
            'status': 'OmniGupt Backend Online',
            'history_count': History.query.count()
        })


@app.route('/cipher', methods=['POST'])
def save_cipher():
    data = request.json or {}
    entry = History(
        session_id=data.get('sessionId', 'anonymous'),
        algorithm=data.get('algo', 'unknown'),
        mode=data.get('mode', 'unknown'),
        operation_type=data.get('type', 'unknown'),
        input_size=data.get('inputSize', 0),
        output_size=data.get('outputSize', 0),
        status=data.get('status', 'success'),
        ip_address=request.remote_addr
    )
    db.session.add(entry)
    db.session.commit()
    return jsonify({'status': 'saved'})

@app.route('/history', methods=['GET'])
def get_history():
    limit = int(request.args.get('limit', 50))
    history = History.query.order_by(History.timestamp.desc()).limit(limit).all()
    return jsonify([h.to_dict() for h in history])

@app.route('/download', methods=['POST'])
def download_history():
    data = request.json or {}
    session_id = data.get('sessionId')
    
    query = History.query.order_by(History.timestamp.desc())
    if session_id:
        query = query.filter_by(session_id=session_id)
    
    history = query.limit(100).all()
    
    content = f"""# OmniGupt Encryption History (Safe Audit Log)
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Total Operations: {len(history)}

## Operations Table

| # | Date/Time | Operation | Method | Mode | Input Size | Output Size | Status |
|---|-----------|-----------|--------|------|------------|-------------|--------|
"""
    
    for i, entry in enumerate(history, 1):
        content += f"| {i} | {entry.timestamp.strftime('%m/%d %H:%M')} | {entry.operation_type.upper()} | {entry.algorithm} | {entry.mode.upper()} | {entry.input_size} | {entry.output_size} | {entry.status} |\n"
    
    content += """

*Safe Audit Log - No plaintexts or secret keys stored 🔒*
Generated by OmniGupt"""
    
    blob = BytesIO(content.encode('utf-8'))
    filename = f"omnigupt_history_{datetime.now().strftime('%Y%m%d_%H%M')}.txt"
    
    return send_file(blob, as_attachment=True, download_name=filename, mimetype='text/plain; charset=utf-8')

with app.app_context():
    # Detect and drop old schema database table
    try:
        db.session.execute(db.text("SELECT original_text FROM history LIMIT 1"))
        db.drop_all()
        print("OmniGupt: Old database schema dropped for migration.")
    except Exception:
        pass
    
    try:
        db.create_all()
    except Exception as e:
        print(f"OmniGupt: Database initialization failed (expected on read-only Vercel environment without /tmp): {e}")

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)


